# 사이킷런

## 사이킷런 소개

* 파이썬용 머신러닝 라이브러리 

* 지도학습 모듈
    - 나이브 베이즈 (Naive Bayes)
    - 의사 결정 트리 (Decision Trees)
    - 서포트 벡터 머신 (Surpport Vector Machines)
    
</br>

* 비지도 학습 모듈
    - 군집화 (Clusting)
    - 가우시한 혼합 모델 (Gaussain mixture models)
    
</br>

* 모델 선택 / 평가 모듈
    - 교차 검증 (cross validation)
    - 모델 평가 (model evaluation)
    
 </br>
 
 * 모델 변환 모듈
     - 파이프라인
     - 특징 추출 (Feature extraction)
     - 데이터 전처리 (Preprocessing data)
     - 차원 축소 (dimensionality reduce)
     

</br>

* 기본 제공 데이터 셋이 있음


### 학습할 모델 

* k-최근접 이웃 분류기 (k-nearest neighbor clssifier) / 지도 학습 </br>
* k-평균 군집화 (k-means Clustering) / 비지도 학습


### 데이터 알아보기

In [3]:
from sklearn.datasets import load_iris ## 붓꽃 데이터

iris_dataset = load_iris() ## 변수에 할당
print("iris_dataset key: {}".format(iris_dataset.keys()))

iris_dataset key: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [4]:
from sklearn.datasets import load_iris ## 붓꽃 데이터

iris_dataset = load_iris() ## 변수에 할당
print(iris_dataset['data'])  ## data 값 확인해보기
print("shape of data: {}".format(iris_dataset['data'].shape))

# (150,4)로 전체 150개의 데이터가 각각 4개의 특징값을 가지고 있음

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
from sklearn.datasets import load_iris ## 붓꽃 데이터

iris_dataset = load_iris() ## 변수에 할당
print(iris_dataset['feature_names']) ## 특징의 이름

## ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
## 꽃받침의 길이, 꽃받침의 너비, 꽃잎 길이, 꽃잎 너비


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
from sklearn.datasets import load_iris ## 붓꽃 데이터

iris_dataset = load_iris() ## 변수에 할당
print(iris_dataset['target']) ## target 값과
print(iris_dataset['target_names'])

## 0,1,2 로 총 3개의 라벨을 가지고 있음
##['setosa' 'versicolor' 'virginica']

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [7]:
from sklearn.datasets import load_iris ## 붓꽃 데이터

iris_dataset = load_iris() ## 변수에 할당
print(iris_dataset['DESCR']) ## Description의 약자로서 해당 데이터에 대한 전체적인 요약 정보를 보여줌 

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

### 사이킷런을 이용한 데이터 분리

In [8]:
from sklearn.model_selection import train_test_split

## train_test_split 함수에 학습데이터와 라벨을 넣으면 정의한 비율로 데이터를 나눈다.

train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'],
                                                                   iris_dataset['target'],
                                                                   test_size = 0.25, # 전체 학습 데이터의 25프로 따로 나눔
                                                                   random_state = 42)


print("shape of train_input: {}".format(train_input.shape))
print("shape of test_input: {}".format(test_input.shape))
print("shape of train_label: {}".format(train_label.shape))
print("shape of test_label: {}".format(test_label.shape))

## shape of train_input: (112, 4)
## shape of test_input: (38, 4)
## shape of train_label: (112,)
## shape of test_label: (38,)

shape of train_input: (112, 4)
shape of test_input: (38, 4)
shape of train_label: (112,)
shape of test_label: (38,)


* 결과를 보면 학습 데이터 (112)개 / 평가 데이터 (38개) => 평가데이터의 크기를 25%로 설정했기 때문에 

</br>
* 학습 데이터와 평가 데이터가 따로 존재하지 않는 경우에는 이처럼 학습 데이터의 일부분을 평가 데이터로 사용

* 평가 데이터가 있는 경우에도 이 함수를 사용해 학습 데이터의 일부를 따로 분리하는 경우가 있다 </br>
    - 학습 데이터와 검증 데이터로 구분하기 위함 
           - 1) 우선 학습 데이터를 사용해 모델을 학습시킨다.
           - 2) 모델에 대해 일차적으로 검증 데이터를 사용해 검증한다.
           - 3) 그 결과를 통해 하이퍼파라미터를 수정한다.
           - 4) 검증 과정/ 학습 과정을 반복한 후 최종적으로 평가 데이터로 평가한다.
        


### 사이킷런을 이용한 지도학습

* 지도 학습 : 각 데이터에 대해 정답이 있는 경우 , 각 데이터의 정답을 예측할 수 있게 학습시키는 과정

* K-근접 이웃 분류기 (k-nearest neighbor classifier)
    - 예측하고자 하는 데이터의 가장 가까운 거리에 있는 데이터의 라벨과 같다고 예측하는 방법
    - 데이터에 대한 사전 지식이 없는 경우의 분류에 많이 사용 됨 
    
    
* K값 : 예측하고자 하는 데이터와 가까운 몇 개의 데이터를 참고할 것인지를 의미 함 


* K- 최근접 이웃 분류기의 특징
    - 데이터에 대한 가정이 없어서 단순함
    - 다목적 분류와 회귀에 좋다
    - 높은 메모리를 요구한다
    - k값이 커지면 계산이 늦어질 수 있다
    - 관련 없는 기능의 data 규모에 민감하다

In [15]:
## 데이터 불러오기
from sklearn.datasets import load_iris

iris_dataset = load_iris()


## 데이터 훈련 / 테스트로 나누기 

from sklearn.model_selection import train_test_split

train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'],
                                                                   iris_dataset['target'],
                                                                   test_size = 0.25,
                                                                   random_state = 42)


## k-nearest neighbor classifier 모델 만들기

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 1) # n_neighbors 인자값 ->> K 값 , 즉 참조할 이웃값 의미

knn.fit(train_input, train_label)

KNeighborsClassifier(algorithm ='auto',
                    leaf_size = 30,
                    metric = 'minkowski',
                    metric_params = None,
                    n_jobs = 1, 
                    n_neighbors = 1,
                    p = 2,
                    weights = 'uniform')



import numpy as np

new_input = np.array([[6.1,2.8,4.7,1.2]])

## 4개의 특징값을 직접 입력해서 넘파이 배열로 만들었다. 
## 리스트 안에 또 하나의 리스트가 있는 방식으로 만들었는데 이렇게 하지 않으면 오류가 발생함

knn.predict(new_input)

## output => array([1])

## 보다시피 1(Versicolor)로 예측하고 있다.

predict_label = knn.predict(test_input)
print(predict_label)

## 실제 결과와 동일한 것의 개수를 평균하면 됨 
print('test accuracy {:.2f}'.format(np.mean(predict_label == test_label)))

## output => test accuracy 1.00

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]
test accuracy 1.00


/Users/tmp/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
/Users/tmp/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be ac

## 비지도 학습

* 데이터에 대한 정답(라벨) 없이 만들 수 있는 모델
</br>

* 데이터에 대한 정답이 없는 경우에 적용하기 적합한 모델이다.

    [군집화] : 데이터를 특성에 따라 여러 집단으로 나누는 것
        
    * 대표 예시 : K-mean Clustering (k-평균 군집화)
    

* K-평균 군집화 훈련 방식
    - 데이터 안에서 대표하는 군집의 중심을 찾는 알고리즘
    - 알고리즘은 계속해서 반복적으로 수행함, 우선 k개 만큼의 중심을 임의로 설정함
    - 모든 데이터를 가장 가까운 중심에 할당한다 / 같은 중심에 할당된 데이터들을 하나의 군집으로 판단한다
    - 각 군집 내 데이터들을 가지고 군집의 중심을 새로 구해서 업데이트 한다
    - 이것을 계속 반복한다 <= 데이터의 변화가 없을 때 까지

In [13]:
## 데이터 불러오기
from sklearn.datasets import load_iris

iris_dataset = load_iris()


## 데이터 훈련 / 테스트로 나누기 

from sklearn.model_selection import train_test_split

train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'],
                                                                   iris_dataset['target'],
                                                                   test_size = 0.25,
                                                                   random_state = 42)

from sklearn.cluster import KMeans
k_means = KMeans(n_clusters=3)

k_means.fit(train_input)

print(k_means.labels_)

[1 1 0 0 0 1 1 0 0 2 0 2 0 2 0 1 2 0 1 1 1 0 0 1 1 1 0 1 0 2 1 0 0 1 0 0 0
 0 2 0 1 0 2 1 1 0 2 1 0 1 1 0 0 2 0 2 2 0 1 1 0 2 1 1 1 0 2 1 2 2 1 0 0 0
 2 2 1 2 0 2 0 0 0 1 0 0 1 0 2 2 1 0 2 2 1 2 1 2 2 2 0 2 0 0 0 0 1 0 0 1 0
 2]


/Users/tmp/opt/anaconda3/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


* skleran이 업데이트 되어서 책에 나온 코드 그대로 안써도 </br>
    k_means = KMeans(n_clusters=3) 하나로 사용가능

* 앞선 설명에 따르면 붓꽃의 라벨을 확인 할 수 없다고 했는데 각 데이터에 라벨링이 되어있다.</br>
    => 이것은 라벨을 의미하는 것이 아니라 3개의 군집으로 k-평균 군집화한 각 군집을 나타낸다.
    

In [1]:
## 데이터 불러오기
from sklearn.datasets import load_iris

iris_dataset = load_iris()


## 데이터 훈련 / 테스트로 나누기 

from sklearn.model_selection import train_test_split

train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'],
                                                                   iris_dataset['target'],
                                                                   test_size = 0.25,
                                                                   random_state = 42)

from sklearn.cluster import KMeans
k_means = KMeans(n_clusters=3)

k_means.fit(train_input)

print("0 cluster:", train_label[k_means.labels_ ==0])
print("1 cluster:", train_label[k_means.labels_ ==1])
print("2 cluster:", train_label[k_means.labels_ ==2])

/Users/tmp/opt/anaconda3/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


0 cluster: [2 1 1 1 2 1 1 1 1 1 2 1 1 1 2 2 2 1 1 1 1 1 2 1 1 1 1 2 1 1 1 2 1 1 1 1 1
 1 1 1 1 1 1 2 2 1 2 1]
1 cluster: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
2 cluster: [2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 1 2 2 2 2]


* 결과를 보면 
    - 0번째 군집은 라벨 1인 데이터들이 주로 분포
    - 1번째 군집은 라벨 0인 데이터들만 분포
    - 2번째 군집은 라벨 2인 데이터들이 주로 분포
    
        => 따라서 새로운 데이터에 대해 예측가능
        
        
* 중요한 점 
    - 항상 결과가 위와 동일하게 나오지 않고 군집화를 진행할 때마다 바뀜
    - 이는 k-평균 군집화 모델 알고리즘 특성 때문에 불가피하게 발생하는 현상 
    - k-평균 군집화의 경우 처음에 초기값을 랜덤으로 설정하고 군집화 과정을 진행하는데 </br>
        => 이러한 과정 때문에 군집화의 순서가 바뀔 수도 있다.

In [17]:
## 데이터 불러오기
from sklearn.datasets import load_iris

iris_dataset = load_iris()


## 데이터 훈련 / 테스트로 나누기 

from sklearn.model_selection import train_test_split

train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'],
                                                                   iris_dataset['target'],
                                                                   test_size = 0.25,
                                                                   random_state = 42)

from sklearn.cluster import KMeans
k_means = KMeans(n_clusters=3)

k_means.fit(train_input)

## 임의의 새로운 데이터를 만들어서 예측을 진행해보기

import numpy as np
new_input = np.array([[6.1,2.8,4.7,1.2]])

# prediction = k_means.predict(new_input)
# print(prediction)

## 실행할 때마다 결과가 바뀜 (띠용?)
## [0]

# 해당 모델의 성능을 측정하기 위해 평가 데이터를 적용시켜 실제 라벨과 비교해 보기

predict_cluster = k_means.predict(test_input)
# print(predict_cluster)
# [0 1 2 0 0 1 0 2 0 0 2 1 1 1 1 0 2 0 0 2 1 0 1 2 2 2 2 2 1 1 1 1 0 1 1 0 0
# 1]

# 평가 데이터를 적용시켜 예측한 군집을 이제 각 붓꽃의 종을 의미하는 라벨값으로 다시 바꿔줘야 실제 라벨과 비교해서 성능 측정할 수 있다.

np_arr = np.array(predict_cluster)
np_arr[np_arr==0], np_arr[np_arr==1], np_arr[np_arr==2] = 3,4,5

np_arr[np_arr ==3] =1
np_arr[np_arr ==4] =0
np_arr[np_arr ==5] =2

predict_label = np_arr.tolist()
print(predict_label)


# [1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0]

# 각 데이터가 속한 군집의 순서를 실제 붓꽃의 라벨로 바꾸어줌 
# 만약 군집의 라벨 분포가 다르게 나온다면 각 군집이 어떤 라벨을 의미하는지 파악 후 해당 라벨로 바꿔줘야 한다.

# 여기서는 0 번째 군집이 라벨 1, 1 번째 군집이 라벨 0, 2 번째 군집이 라벨 2를 의미한다

# 이를 변경할 때는 임시 저장을 위해 군집의 순서값 3,4,5 를 넘파이 배열로 우선 만들어준다.
# 이후 군집 3을 1로 , 군집 4를 0으로 , 군집 5를 2로 바꾸어줌

print('test accuracy {:.2f}'.format(np.mean(predict_label == test_label)))

## 실행 시 마다 결과가 바뀜..아놔 
## 높은 실행결과 : 0.95

[1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0]
test accuracy 0.95


/Users/tmp/opt/anaconda3/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
